spring:
  application:
    name: service-system
  profiles:
    active: prod
  jackson:
    generator:
      writeNumbersAsStrings: true
    # 返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8