spring:
  application:
    name: service-system
  profiles:
    active: prod
  jackson:
    # 返回json的全局时间格式
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 1800000
    password:
    jedis:
      pool:
        # 最大连接数
        max-active: 20
        # 最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        # 最大空闲
        max-idle: 5
        # 最小空闲
        min-idle: 0