# 服务端口
server:
  port: 1128

spring:
  # 服务名
  application:
    name: service-gateway-1128
  # nacos服务地址
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    # 使用服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true
      # service-system 模块配置
      # 设置路由id
      routes: [{id: service-system, uri: lb://service-system, predicates: Path=/*/system/**}]
